# Change these first
owner: Sampiiiii # Your GitHub organization or username, where this repository lives
repo: services-uptime # The name of this repository

sites:
  - name: Sampiiiii.dev
    url: https://sampiiiii.dev
  - name: Gitlab
    url: https://gitlab.sampiiiii.com
  - name: Nextcloud
    url: https://nextcloud.sampiiiii.com
  - name: Drone
    url: https://drone.sampiiiii.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.sampiiiii.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "This is my uptime page for all my currently hosted servies powered by GitHub"
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
